/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Subject-agnostic schema for all standard node map files across Science, Maths, DT, English and future subjects. One file per ACARA/IB/curriculum standard. Replaces earlier subject-specific schemas.
 */
export interface NodeFile {
  /**
   * Year level string. e.g. '7', '7-8' for banded curricula.
   */
  year_level: string;
  /**
   * Subject area. e.g. 'Science', 'Mathematics', 'Digital Technologies', 'English'
   */
  subject: string;
  /**
   * Curriculum version. e.g. 'ACARA v9', 'MYP'
   */
  curriculum: string;
  standard: {
    /**
     * Curriculum descriptor code. e.g. 'AC9S7U01', 'AC9TDI8P05'
     */
    code: string;
    /**
     * Short human-readable title. e.g. 'Classification and Biodiversity'
     */
    title: string;
    /**
     * Verbatim curriculum descriptor text.
     */
    description: string;
    /**
     * Optional. Curriculum strand label. e.g. 'Understanding', 'Processes and Production', 'Human Endeavour', 'Inquiry Skills', 'Number and Algebra'. Free text — not constrained to a fixed enum to allow cross-subject use.
     */
    strand?: string;
    /**
     * Optional. Planning mode. A = concept-certifying (shared conceptual sequence, assessment independent of task). B = capability-certifying (process/inquiry sequence, thinking only legible through the work). Defaults to A for U-strand standards.
     */
    mode?: "A" | "B";
    /**
     * What students are assumed to know before this unit. Derived from curriculum progression chain.
     */
    prior_knowledge: string;
    /**
     * Fixed conceptual endpoint for all students — the shared assessment target. Framed as 'Students...'. Replaces y_goal. Must not be exceeded by any node or width tier.
     */
    progression_endpoint: string;
    /**
     * Ordered sequence of conceptual waypoints from assumed prior to progression_endpoint. All nodes are mandatory for all students.
     *
     * @minItems 3
     */
    nodes: [Node, Node, Node, ...Node[]];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Node {
  /**
   * Sequential node number within this standard. Starts at 1.
   */
  id: number;
  /**
   * Short display name for the node. e.g. 'Purpose of classification'
   */
  label: string;
  /**
   * Conceptual position reached at this node — framed as 'Students can...'. This is where students are at this waypoint on the progression toward the endpoint. Replaces y_description.
   */
  progression_checkpoint: string;
  /**
   * Minimum construction required before advancing to the next node. Non-negotiable floor — certifies readiness. Set by the command term of the descriptor. Replaces xmin.
   */
  minimum_width: string;
  /**
   * Full descriptor scope. Standard construction for a typical class at this node. Broader integration than minimum_width but same concept. Replaces width_core.
   */
  typical_width: string;
  /**
   * Enrichment directions — extended phenomena, contexts or transfer tasks. Each item is a discrete enrichment direction. Must add phenomena or context — not depth-on-fewer-phenomena. Example directions only, not exhaustive. Replaces width_enrich_options.
   *
   * @minItems 1
   */
  wider: [string, ...string[]];
  /**
   * True if this is a hinge concept — a node where misconceptions cluster, downstream nodes depend on it, and width investment pays off disproportionately.
   */
  hinge: boolean;
  /**
   * Required if hinge is true. Explains why this is a hinge — dependency chain, misconception gateway, assessment sensitivity. Null if hinge is false.
   */
  hinge_reason: string | null;
  /**
   * 2-3 assessable evidence statements anchored to minimum_width threshold. Observable, measurable indicators of what a teacher looks for to confirm the waypoint is met. Width-agnostic — same criteria for all students regardless of width level.
   *
   * @minItems 2
   * @maxItems 3
   */
  success_criteria: [string, string] | [string, string, string];
  /**
   * Optional. Related curriculum codes — inquiry skills, human endeavour, cross-strand links. Used for future lesson prompt enrichment and sharing ecosystem filtering. Replaces inquiry_links and endeavour_links.
   */
  related_standards?: string[];
  /**
   * Optional. Free-text notes for curriculum designers — flags non-standard decisions, known misconceptions, pedagogical caveats.
   */
  notes?: string;
  [k: string]: unknown;
}
