/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for subject/band width tiers lookup files. Flat by descriptor code. Renderer merges with node map files at runtime via code key. One file per subject/band. Consistent naming with node_schema_v2.json.
 */
export interface WidthTiers {
  description: string;
  /**
   * e.g. 'Science', 'Digital Technologies', 'Mathematics'
   */
  subject: string;
  /**
   * e.g. 'ACARA v9'
   */
  curriculum: string;
  /**
   * Year band. e.g. '7', '7-8', '9-10'
   */
  band: string;
  /**
   * Traceability — records which rules were used to generate this file.
   */
  generation_rules?: {
    /**
     * Version of width_generation_prompt.md used. e.g. 'v1.0'
     */
    prompt_version?: string;
    /**
     * Primary axis used for width variation in this file.
     */
    primary_width_axis?: "phenomena_contexts" | "task_contexts" | "depth_fallback" | "mixed";
    [k: string]: unknown;
  };
  width_notes: {
    /**
     * Definition of the minimum width tier for this file.
     */
    minimum_width: string;
    /**
     * Definition of the typical width tier for this file.
     */
    typical_width: string;
    /**
     * Definition of the enrichment width tier for this file.
     */
    wider: string;
    /**
     * Note on how elaborations were used as source data.
     */
    elaborations: string;
    [k: string]: unknown;
  };
  /**
   * Flat lookup keyed by curriculum descriptor code.
   */
  standards: {
    [k: string]: WidthEntry;
  };
  [k: string]: unknown;
}
export interface WidthEntry {
  /**
   * Optional. Curriculum strand label. e.g. 'Understanding', 'Processes and Production'. Free text — matches node_schema_v2 strand field.
   */
  strand?: string;
  /**
   * Primary axis driving width variation. phenomena_contexts = number of phenomena or real-world contexts (primary for Understanding strand). task_contexts = range of tasks or application contexts (primary for Processes strand). depth_fallback = used only when breadth is not meaningfully variable.
   */
  width_axis: "phenomena_contexts" | "task_contexts" | "depth_fallback";
  /**
   * Minimum construction required to certify this standard. Set by the command term in the descriptor — the non-negotiable floor. For Understanding: minimum phenomena/contexts. For Processes: encounter/recognise level in narrowest context.
   */
  minimum_width: string;
  /**
   * Full descriptor scope grounded in most common elaboration cases. What a well-taught student in a standard class would reach.
   */
  typical_width: string;
  /**
   * Enrichment directions — extended phenomena, contexts or cases. Must add phenomena or context — not depth-on-fewer-phenomena. Example directions only, not exhaustive or prescriptive.
   *
   * @minItems 2
   */
  wider: [string, string, ...string[]];
  /**
   * Curriculum elaborations verbatim. Source data for the width tiers.
   */
  elaborations: string[];
  /**
   * Optional. Flags non-standard decisions — e.g. depth_fallback used because breadth is not variable, or enrichment inferred beyond elaborations.
   */
  width_notes?: string;
  [k: string]: unknown;
}
